# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/design_CALY_design_aplikacja_wra_0_0.xci
# IP: The module: 'design_CALY_design_aplikacja_wra_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/design_aplikacja_design_lcd_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_lcd_wrapper_0_0 || ORIG_REF_NAME==design_aplikacja_design_lcd_wrapper_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/design_aplikacja_design_multikontrole_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_multikontrole_0_0 || ORIG_REF_NAME==design_aplikacja_design_multikontrole_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_PBLAZE_DOWNLOADER_0_0/design_multikontroler_PBLAZE_DOWNLOADER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_PBLAZE_DOWNLOADER_0_0 || ORIG_REF_NAME==design_multikontroler_PBLAZE_DOWNLOADER_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_PBlazeZH_0_0/design_multikontroler_PBlazeZH_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_PBlazeZH_0_0 || ORIG_REF_NAME==design_multikontroler_PBlazeZH_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_Mux_Multiplekser_0_0/design_multikontroler_Mux_Multiplekser_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_Mux_Multiplekser_0_0 || ORIG_REF_NAME==design_multikontroler_Mux_Multiplekser_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_DEKODER_ADRESOWY_0_0/design_multikontroler_DEKODER_ADRESOWY_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_DEKODER_ADRESOWY_0_0 || ORIG_REF_NAME==design_multikontroler_DEKODER_ADRESOWY_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_xup_or2_0_0_0/design_multikontroler_xup_or2_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_xup_or2_0_0_0 || ORIG_REF_NAME==design_multikontroler_xup_or2_0_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_xup_or2_1_0_0/design_multikontroler_xup_or2_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_xup_or2_1_0_0 || ORIG_REF_NAME==design_multikontroler_xup_or2_1_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/design_aplikacja_design_on_off_downlo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_on_off_downlo_0_0 || ORIG_REF_NAME==design_aplikacja_design_on_off_downlo_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/src/design_on_off_downloader_uart_0_0_0/design_on_off_downloader_uart_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_on_off_downloader_uart_0_0_0 || ORIG_REF_NAME==design_on_off_downloader_uart_0_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/src/design_on_off_downloader_dekoder_0_0_0/design_on_off_downloader_dekoder_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_on_off_downloader_dekoder_0_0_0 || ORIG_REF_NAME==design_on_off_downloader_dekoder_0_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_bin2bcd_0_0/design_aplikacja_bin2bcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_bin2bcd_0_0 || ORIG_REF_NAME==design_aplikacja_bin2bcd_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_SERIAL_RX_FIFO_0_0/design_aplikacja_SERIAL_RX_FIFO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_SERIAL_RX_FIFO_0_0 || ORIG_REF_NAME==design_aplikacja_SERIAL_RX_FIFO_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_SERIAL_TX_FIFO_0_0/design_aplikacja_SERIAL_TX_FIFO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_SERIAL_TX_FIFO_0_0 || ORIG_REF_NAME==design_aplikacja_SERIAL_TX_FIFO_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_DS18B20_0_0/design_aplikacja_DS18B20_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_DS18B20_0_0 || ORIG_REF_NAME==design_aplikacja_DS18B20_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_LED_0_0/design_aplikacja_LED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_LED_0_0 || ORIG_REF_NAME==design_aplikacja_LED_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_LED_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_LED_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/design_aplikacja_design_clock_1_wrapp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_clock_1_wrapp_0_0 || ORIG_REF_NAME==design_aplikacja_design_clock_1_wrapp_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_SERIAL_CLOCK_0_0/design_clock_1_SERIAL_CLOCK_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_clock_1_SERIAL_CLOCK_0_0 || ORIG_REF_NAME==design_clock_1_SERIAL_CLOCK_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_Clock_0_0_1/design_clock_1_Clock_0_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_clock_1_Clock_0_0_1 || ORIG_REF_NAME==design_clock_1_Clock_0_0_1} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_Clock_0_0_1/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_Clock_0_0_1/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/src/design_lcd_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/src/design_on_off_downloader_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_ooc.xdc

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/design_CALY_design_aplikacja_wra_0_0.xci
# IP: The module: 'design_CALY_design_aplikacja_wra_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/design_aplikacja_design_lcd_wrapper_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_lcd_wrapper_0_0 || ORIG_REF_NAME==design_aplikacja_design_lcd_wrapper_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/design_aplikacja_design_multikontrole_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_multikontrole_0_0 || ORIG_REF_NAME==design_aplikacja_design_multikontrole_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_PBLAZE_DOWNLOADER_0_0/design_multikontroler_PBLAZE_DOWNLOADER_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_PBLAZE_DOWNLOADER_0_0 || ORIG_REF_NAME==design_multikontroler_PBLAZE_DOWNLOADER_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_PBlazeZH_0_0/design_multikontroler_PBlazeZH_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_PBlazeZH_0_0 || ORIG_REF_NAME==design_multikontroler_PBlazeZH_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_Mux_Multiplekser_0_0/design_multikontroler_Mux_Multiplekser_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_Mux_Multiplekser_0_0 || ORIG_REF_NAME==design_multikontroler_Mux_Multiplekser_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_DEKODER_ADRESOWY_0_0/design_multikontroler_DEKODER_ADRESOWY_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_DEKODER_ADRESOWY_0_0 || ORIG_REF_NAME==design_multikontroler_DEKODER_ADRESOWY_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_xup_or2_0_0_0/design_multikontroler_xup_or2_0_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_xup_or2_0_0_0 || ORIG_REF_NAME==design_multikontroler_xup_or2_0_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_xup_or2_1_0_0/design_multikontroler_xup_or2_1_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_multikontroler_xup_or2_1_0_0 || ORIG_REF_NAME==design_multikontroler_xup_or2_1_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/design_aplikacja_design_on_off_downlo_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_on_off_downlo_0_0 || ORIG_REF_NAME==design_aplikacja_design_on_off_downlo_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/src/design_on_off_downloader_uart_0_0_0/design_on_off_downloader_uart_0_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_on_off_downloader_uart_0_0_0 || ORIG_REF_NAME==design_on_off_downloader_uart_0_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/src/design_on_off_downloader_dekoder_0_0_0/design_on_off_downloader_dekoder_0_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_on_off_downloader_dekoder_0_0_0 || ORIG_REF_NAME==design_on_off_downloader_dekoder_0_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_bin2bcd_0_0/design_aplikacja_bin2bcd_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_bin2bcd_0_0 || ORIG_REF_NAME==design_aplikacja_bin2bcd_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_SERIAL_RX_FIFO_0_0/design_aplikacja_SERIAL_RX_FIFO_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_SERIAL_RX_FIFO_0_0 || ORIG_REF_NAME==design_aplikacja_SERIAL_RX_FIFO_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_SERIAL_TX_FIFO_0_0/design_aplikacja_SERIAL_TX_FIFO_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_SERIAL_TX_FIFO_0_0 || ORIG_REF_NAME==design_aplikacja_SERIAL_TX_FIFO_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_DS18B20_0_0/design_aplikacja_DS18B20_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_DS18B20_0_0 || ORIG_REF_NAME==design_aplikacja_DS18B20_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_LED_0_0/design_aplikacja_LED_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_LED_0_0 || ORIG_REF_NAME==design_aplikacja_LED_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_LED_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_LED_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/design_aplikacja_design_clock_1_wrapp_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_aplikacja_design_clock_1_wrapp_0_0 || ORIG_REF_NAME==design_aplikacja_design_clock_1_wrapp_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_SERIAL_CLOCK_0_0/design_clock_1_SERIAL_CLOCK_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_clock_1_SERIAL_CLOCK_0_0 || ORIG_REF_NAME==design_clock_1_SERIAL_CLOCK_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_Clock_0_0_1/design_clock_1_Clock_0_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_clock_1_Clock_0_0_1 || ORIG_REF_NAME==design_clock_1_Clock_0_0_1} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_Clock_0_0_1/src/design_lcd_laczenie_LCD_0_0/design_lcd_laczenie_LCD_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_laczenie_LCD_0_0 || ORIG_REF_NAME==design_lcd_laczenie_LCD_0_0} -quiet] -quiet

# IP: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_Clock_0_0_1/src/design_lcd_lcd_putchar_8_0_0/design_lcd_lcd_putchar_8_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lcd_lcd_putchar_8_0_0 || ORIG_REF_NAME==design_lcd_lcd_putchar_8_0_0} -quiet] -quiet

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_lcd_wrapper_0_0/src/design_lcd_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_multikontrole_0_0/src/design_multikontroler_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_on_off_downlo_0_0/src/design_on_off_downloader_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_design_clock_1_wrapp_0_0/src/design_clock_1_ooc.xdc

# XDC: c:/Users/Admin/repozytorium/project_1/project.src/CALY/design_CALY/ip/design_CALY_design_aplikacja_wra_0_0/src/design_aplikacja_ooc.xdc
